/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as WhatWeHaulRouteImport } from './routes/what-we-haul'
import { Route as JobsClairemontBoxSpringsRouteImport } from './routes/jobs.clairemont-box-springs'
import { Route as ServiceAreaSlugRouteImport } from './routes/service-area_.$slug'
import { Route as WhatWeHaulSlugRouteImport } from './routes/what-we-haul_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeHaulRoute = WhatWeHaulRouteImport.update({
  id: '/what-we-haul',
  path: '/what-we-haul',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsClairemontBoxSpringsRoute =
  JobsClairemontBoxSpringsRouteImport.update({
    id: '/jobs/clairemont-box-springs',
    path: '/jobs/clairemont-box-springs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreaSlugRoute = ServiceAreaSlugRouteImport.update({
  id: '/service-area_/$slug',
  path: '/service-area/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeHaulSlugRoute = WhatWeHaulSlugRouteImport.update({
  id: '/what-we-haul_/$slug',
  path: '/what-we-haul/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/service-area': typeof ServiceAreaRoute
  '/what-we-haul': typeof WhatWeHaulRoute
  '/jobs/clairemont-box-springs': typeof JobsClairemontBoxSpringsRoute
  '/service-area/$slug': typeof ServiceAreaSlugRoute
  '/what-we-haul/$slug': typeof WhatWeHaulSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/service-area': typeof ServiceAreaRoute
  '/what-we-haul': typeof WhatWeHaulRoute
  '/jobs/clairemont-box-springs': typeof JobsClairemontBoxSpringsRoute
  '/service-area/$slug': typeof ServiceAreaSlugRoute
  '/what-we-haul/$slug': typeof WhatWeHaulSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/service-area': typeof ServiceAreaRoute
  '/what-we-haul': typeof WhatWeHaulRoute
  '/jobs/clairemont-box-springs': typeof JobsClairemontBoxSpringsRoute
  '/service-area_/$slug': typeof ServiceAreaSlugRoute
  '/what-we-haul_/$slug': typeof WhatWeHaulSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/service-area'
    | '/what-we-haul'
    | '/jobs/clairemont-box-springs'
    | '/service-area/$slug'
    | '/what-we-haul/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/service-area'
    | '/what-we-haul'
    | '/jobs/clairemont-box-springs'
    | '/service-area/$slug'
    | '/what-we-haul/$slug'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/service-area'
    | '/what-we-haul'
    | '/jobs/clairemont-box-springs'
    | '/service-area_/$slug'
    | '/what-we-haul_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  WhatWeHaulRoute: typeof WhatWeHaulRoute
  JobsClairemontBoxSpringsRoute: typeof JobsClairemontBoxSpringsRoute
  ServiceAreaSlugRoute: typeof ServiceAreaSlugRoute
  WhatWeHaulSlugRoute: typeof WhatWeHaulSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-haul': {
      id: '/what-we-haul'
      path: '/what-we-haul'
      fullPath: '/what-we-haul'
      preLoaderRoute: typeof WhatWeHaulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/clairemont-box-springs': {
      id: '/jobs/clairemont-box-springs'
      path: '/jobs/clairemont-box-springs'
      fullPath: '/jobs/clairemont-box-springs'
      preLoaderRoute: typeof JobsClairemontBoxSpringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area_/$slug': {
      id: '/service-area_/$slug'
      path: '/service-area/$slug'
      fullPath: '/service-area/$slug'
      preLoaderRoute: typeof ServiceAreaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-haul_/$slug': {
      id: '/what-we-haul_/$slug'
      path: '/what-we-haul/$slug'
      fullPath: '/what-we-haul/$slug'
      preLoaderRoute: typeof WhatWeHaulSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  WhatWeHaulRoute: WhatWeHaulRoute,
  JobsClairemontBoxSpringsRoute: JobsClairemontBoxSpringsRoute,
  ServiceAreaSlugRoute: ServiceAreaSlugRoute,
  WhatWeHaulSlugRoute: WhatWeHaulSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
